### ISSUE TITLE
Support enumConstants extracting

### ISSUE THREAD

**Issue by Damtev** [UnitTestBot/java-compilation-database#151]
Sometimes it is required to extract [`enumConstants`](https://docs.oracle.com/javase/specs/jls/se20/html/jls-8.html#jls-8.9.1) of the particular enum class. In `Java`, it is possible via the `java.lang.Class#getEnumConstants` method. It is proposed to add the same feature to `jacodb`.

**Comment by lehvolk** [comment]
There already exists extension `JcClassOrInterface.enumValues` but with bug
